/*
  DO NOT MODIFY - This file has been generated by https://github.com/flemay/Fomantic-UI-Meteorize
*/

Package.describe({
  name: 'mrmowgli:fomantic-ui',
  version: '2.3.2',
  summary: 'Unofficial Fomantic UI Integration for Meteor',
  git: 'git@github.com:mrmowgli/Fomantic-UI-Meteor.git',
  documentation: 'README.md'
});

Package.registerBuildPlugin({
  name: "generateFomanticUi",
  use: [
    'ecmascript@0.1.5',
    'ejson@1.0.6',
    'mrmowgli:fomantic-ui-data@2.3.2'
  ],
  sources: [
    'fomantic-ui.js',
    'data/definitions-data.js',
    'data/themes-data.js',
    'data/sites-data.js',
    'data/custom-fomantic-data.js',
    'plugins/file-handler.js',
    'plugins/definitions-generator.js',
    'plugins/themes-generator.js',
    'plugins/sites-generator.js',
    'plugins/custom-fomantic-json-generator.js',
    'plugins/generator.js'
  ],
  npmDependencies: {
    "lodash": "3.6.0",
    "diff": "1.3.2"
  }
});

Package.onUse(function (api) {
  api.use('isobuild:compiler-plugin@1.0.0');
});
